// <auto-generated />
using BikeForeverApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BikeForeverApi.Migrations
{
    [DbContext(typeof(BikeForeverContext))]
    partial class BikeForeverContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("BikeForeverApi.Models.PostItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Height");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Subscribers");

                    b.Property<string>("Tags");

                    b.Property<string>("Title");

                    b.Property<string>("UploadTime");

                    b.Property<string>("UserId");

                    b.Property<string>("Width");

                    b.HasKey("Id");

                    b.ToTable("PostItem");
                });
#pragma warning restore 612, 618
        }
    }
}
